---
title: "Untitled"
author: "Yijie Wu"
date: "5/15/2021"
output: html_document
---



```{r}
S0 <- 100  # Initial stock price
T <- 0.5  # time in years
Num_Periods = 1000
dt <- T/Num_Periods # time
mu <- 0   # Annualized drift
sigma <- .3 # Annualized volatility 
Num_Paths = 1000

X <- matrix(rnorm(n=Num_Paths*Num_Periods, (mu - (sigma^2)/2)*dt, sigma*sqrt(dt)),Num_Paths,Num_Periods)
X <- cbind(rep(0,Num_Paths),t(apply(X,1,cumsum)))
simu.path <- S0*exp(X)
Time_Periods = seq(0,T,dt)
write.csv(simu.path,'stock_price.csv')
#GBM=t(GBM)
  #test.path<-GBM.process(spot = 100,drift = 0.1,sigma = 0.3,num = 2000,tau = 0.5)
  #plot(test.path,type = "l")
```

```{r}
C_Price <- function(S, K, r, q, T, sigma) {
  d1  <-  (log(S/K) + (r - q + (sigma^2)/2)*T) / (sigma*sqrt(T))
  d2  <-  d1 - sigma*sqrt(T)
  c_Price <- S * exp(-q*T) *  pnorm(d1)  - K*exp(-r*T)*pnorm(d2)
  #C_Delta <- exp(-q*T) *  pnorm(d1) 
  #return(cbind(C_Price, C_Delta))
  return (c_Price)
}

#p0=C_Price(100,100,0.01,0.01,0.5,0.3)
#c0=p0
C_Price(100,100,0.01,0.01,0.5,0.3)
```

```{r}
C_Delta <- function(S, K, r, q, T, sigma) {
  d1  <-  (log(S/K) + (r - q + (sigma^2)/2)*T) / (sigma*sqrt(T))
  d2  <-  d1 - sigma*sqrt(T)
  #C_Price <- S * exp(-q*T) *  pnorm(d1)  - K*exp(-r*T)*pnorm(d2)
  C_Delta <- exp(-q*T) *  pnorm(d1) 
  #return(cbind(C_Price, C_Delta))
  return (C_Delta)
}
```


```{r}
#replicate(n,object)  creates n columns of the object
    premium<-C_Price(S = 100,K = 100,r = 0.01,q=0.01,T = 0.5,sigma=0.2)
    #simu.path<-replicate(100000, GBM.process(spot = 100,drift = 0,sigma = 0.3,num = 2000,tau = 0.5))
    
    simu.delta<-matrix(0,nrow = nrow(simu.path),ncol = ncol(simu.path))#every delta on every point
    period <- nrow(simu.path)
    for(i in 1:nrow(simu.path)){
      for(k in 1:ncol(simu.path)){
        simu.delta[i,k]<-C_Delta(S = simu.path[i,k],K = 100,r = 0.01,q=0.01,T = 1-(k-1)/period,sigma=0.2)
      }
    }
  simu.delta
    #dif.hedge<-apply(simu.delta,2,diff)#difference between two hedging positions, additional purchase or sell
```


```{r}
r=0.01
c=0.01
Pt<-matrix(0,nrow = nrow(simu.path),ncol = ncol(simu.path))
for(i in 1:nrow(Pt)){
      Pt[i,1]<-premium
    }
    for(i in 1:nrow(Pt)){
      for (k in 2:ncol(Pt)) {
        Pt[i,k]<-Pt[i,k-1]+(Pt[i,k-1]-simu.delta[i,k-1]*simu.path[i,k-1])*r*0.5/2000+simu.delta[i,k-1]*(simu.path[i,k]+c*simu.path[i,k-1]*0.5/2000-simu.path[i,k-1])
      }
    }
```


```{r}
l <- list()
i <- 1
while(i<=100000) {
    l[[i]] <-tail(Pt[i,],n=1)-max(tail(simu.path[i,],n=1)-k,0)
    i <- i + 1
}
#pl=tail(Pt[,1],n=1)-max(tail(simu.path[,1],n=1)-k,0)
#pl

```

```{r}
hist(as.numeric(unlist(l)))
```
```{r}
library(ggplot2)
# Basic histogram
ggplot(data.frame(matrix(unlist(l), nrow=length(l), byrow=TRUE)),aes(x)) + geom_histogram()
# Change the width of bins
ggplot(df, aes(x=weight)) + 
  geom_histogram(binwidth=1)
# Change colors
p<-ggplot(df, aes(x=weight)) + 
  geom_histogram(color="black", fill="white")
p
```
```{r}
data=data.frame(matrix(unlist(l), nrow=length(l), byrow=TRUE))

```

