---
title: "Exam"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
```{r}
library(gapminder)
library(dplyr)
library(forcats)
library(ggplot2)
df <- gapminder %>%
  filter (year == 2007) %>%
  count(continent) %>% 
  arrange(desc(n))

ggplot(df, aes(y=fct_infreq(continent), x=n)) + 
  geom_bar(stat = "identity", width=0.2) +
  coord_flip() +
  xlab("Continent") + 
  ylab("Count of countries")
# missing ranking
```

## Question 2
```{r}
df <- gapminder %>%
  filter (year == 2007) 
ggplot(data = df,) +
  geom_point(aes(x=gdpPercap, y=lifeExp, size = pop,color = continent)) +
  scale_x_continuous(trans = "log10") + 
  xlab("gdp per capita") + 
  ylab("Life expectancy at birth")
```

## Question 3
```{r}
df <- gapminder %>%
  filter (continent == 'Europe') 
ggplot(data = df)+
  geom_line(mapping = aes(x = year, y = lifeExp)) + facet_wrap(vars(country), nrow = 2) + 
  xlab("Year") + 
  ylab("Life expectancy at birth")
```

## Question 4
```{r}
library(RColorBrewer)
df <- gapminder %>%
  filter (year == 1957) 
ggplot(data = df,aes(x = continent, y = lifeExp)) +
  geom_violin(aes(fill=continent)) +
  geom_point(mapping = aes(group=continent), position = "jitter", alpha = 0.5,color="black") + 
  scale_colour_brewer(palette = "set2") + 
  xlab("Continent") + 
  ylab("Life expectancy at birth")
```

## Question 5
```{r}
library(patchwork)
df_1957 <- gapminder %>%
  filter (year == 1957,!(continent == 'Oceania'))
df_2007 <- gapminder %>%
  filter (year == 2007,!(continent == 'Oceania'))

p1 <- ggplot(df_1957,aes(x = lifeExp, color = continent,fill= continent)) +
  geom_density(adjust = 1) + 
  scale_colour_brewer(palette = "set1") +
  xlim(30, 90)

p2 <- ggplot(df_2007,aes(x = lifeExp, color = continent,fill= continent)) +
  geom_density(adjust = 1) +
  scale_colour_brewer(palette = "set1") +
  xlim(30, 90)

p1 + p2
```

