---
title: "Cheetsheet_1"
author: "Qian Zhang"
date: "2020年12月10日"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## ggplot: Canvas
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy))
```

## ggplot: scatter plot
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
geom_point()
```

## ggplot: color the points by categories
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color= class)) +
geom_point()
```

## ggplot: color the points
```{r}
ggplot(data = mpg) +
geom_point(mapping = aes(x = displ, y = hwy), color ="blue")
```

## ggplot: Facets partition the data and create small multiple plots side by side
```{r}
ggplot(data = mpg)+
geom_point(mapping = aes(x = displ, y = hwy)) +
facet_wrap(vars(class), nrow = 2)
```

## ggplot: small multiple plots of two variables for every values
```{r}
ggplot(data = mpg)+
geom_point(mapping = aes(x = displ, y = hwy)) +
facet_grid(drv ~ cyl, labeller = label_both)
```


```{r}
ggplot(data = mpg)+
geom_point(mapping = aes(x = displ, y = hwy)) +
facet_grid(drv ~ ., labeller = label_both)
```

```{r}
ggplot(data = mpg)+
geom_point(mapping = aes(x = displ, y = hwy)) +
facet_grid(. ~ cyl, labeller = label_both)
```

