---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


Method 1:
```{r}
seq_1 = 0
seq_2 = 1
k = 5
for (i in 2:k){
  temp = seq_2
  seq_2 = seq_2+seq_1
  seq_1 = temp
}
print(paste('The Fibonacchi Number for k = ',k,'is ',seq_2))
```
Method 2:
```{r}
A = matrix(
  c(1,1,1,0),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)
matrix_1 = matrix(
  c(1,0),
  nrow = 2,
  ncol = 1,
  byrow = TRUE
)
k = 5
for (i in 2:k){
  matrix_2 = A%*%matrix_1
  matrix_1 = matrix_2
}
print(paste('The Fibonacchi Number for k = ',k,'is ',matrix_2[1]))
```

Method 3:
```{r}
A = matrix(
  c(1,1,1,0),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)
ev = eigen(A)
eigenvalues = ev$values
eigenvectors = ev$vectors
eigenvectors_inverse = solve(eigenvectors)


eigenvalues_matrix = matrix(
  c(eigenvalues[1],0,0,eigenvalues[2]),
  nrow = 2,
  ncol = 2,
  byrow = TRUE
)
k = 5
A_k = eigenvectors %*% eigenvalues_matrix **(k-2) %*% eigenvectors_inverse
A_final = A_k %*% A
print(paste('The Fibonacchi Number for k = ',k,'is ',A_final[1]))
```

