% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 1},
  pdfauthor={Group 11},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Assignment 1}
\author{Group 11}
\date{2021/5/6}

\begin{document}
\maketitle

\hypertarget{question-1}{%
\section{Question 1}\label{question-1}}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  \(\phi(x)=x_1^2+x_2^2\) \newline
\item
  \(\phi(x)=x_1x_2\) \newline
\item
  \(\phi_1(x)=x_1\), \(\phi_2(x)=x_1^2\)
\end{enumerate}

\hypertarget{question-2}{%
\section{Question 2}\label{question-2}}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\AttributeTok{file =} \StringTok{"Tahoe\_Healthcare\_Data.csv"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{allad}\OtherTok{\textless{}{-}}\FunctionTok{sum}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{readmit30) }\CommentTok{\# 998 (1: readmitted, 0: not readmitted)}
\NormalTok{none}\OtherTok{\textless{}{-}}\NormalTok{allad}\SpecialCharTok{*}\DecValTok{8000}
\NormalTok{none}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7984000
\end{verbatim}

Taking the data-set as representative of what will happen in a given
year if nothing is done to reduce the readmissions rate, there are 998
re-admitted patients. Given that the estimated loss in Medicare
reimbursements would rise to \$8,000 per re-admitted patient, we obtain
the total cost as \$7,984,000.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{count}\OtherTok{\textless{}{-}}\FunctionTok{count}\NormalTok{(data)}
\CommentTok{\# Total cost if CareTracker was implemented for all AMI patients}
\NormalTok{max}\OtherTok{\textless{}{-}}\NormalTok{count}\SpecialCharTok{*}\DecValTok{1200}\SpecialCharTok{+}\NormalTok{allad}\SpecialCharTok{*}\DecValTok{8000}\SpecialCharTok{*}\NormalTok{.}\DecValTok{6}  \CommentTok{\# CareTracker cost $1,200 per patient, }
                              \CommentTok{\# can reduce the incidence of readmissions by 40\%}
\NormalTok{netprofit}\OtherTok{\textless{}{-}}\NormalTok{none}\SpecialCharTok{{-}}\NormalTok{max }\CommentTok{\# Net change in cost}
\NormalTok{netprofit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          n
## 1 -2064800
\end{verbatim}

Tahoe should not implement CareTracker for all AMI patients because the
net profit is -2064800, which is much smaller than 0.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cost when nothing done {-} Cost when implementing CareTracker }
\CommentTok{\# for exactly 998 re{-}admitted patients}
\NormalTok{none}\SpecialCharTok{{-}}\FunctionTok{sum}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{readmit30)}\SpecialCharTok{*}\NormalTok{(}\DecValTok{8000}\SpecialCharTok{*}\NormalTok{.}\DecValTok{6}\SpecialCharTok{+}\DecValTok{1200}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1996000
\end{verbatim}

If Tahoe had perfect foresight regarding re-admitted patients, they
could explicitly implement CareTracker for 998 re-admitted patients and
reduced the incidence of readmissions among these patients by 40\%.
Therefore, they will save \$1,996,000 as a upper bound.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{25}\SpecialCharTok{:}\DecValTok{100}\NormalTok{)}
\NormalTok{list1 }\OtherTok{=} \FunctionTok{c}\NormalTok{() }\CommentTok{\# store cost savings}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{25}\SpecialCharTok{:}\DecValTok{100}\NormalTok{) \{}
  \CommentTok{\# filter out the patients with higher severity score}
\NormalTok{  T1}\OtherTok{\textless{}{-}}\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{severity.score}\SpecialCharTok{\textgreater{}}\NormalTok{i,] }
  \CommentTok{\# number of true re{-}admitted patients among the selected patients}
\NormalTok{  ad}\OtherTok{\textless{}{-}}\FunctionTok{sum}\NormalTok{(T1}\SpecialCharTok{$}\NormalTok{readmit30)}
  \CommentTok{\# saved cost {-} implementation cost = final cost saving}
\NormalTok{  list1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(list1, ad}\SpecialCharTok{*}\DecValTok{8000}\SpecialCharTok{*}\NormalTok{.}\DecValTok{4}\SpecialCharTok{{-}}\FunctionTok{dim}\NormalTok{(T1)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{*}\DecValTok{1200}\NormalTok{)}
\NormalTok{\}}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{seq}\NormalTok{(}\DecValTok{25}\NormalTok{, }\DecValTok{100}\NormalTok{), }\AttributeTok{y =}\NormalTok{ list1)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{limits=}\FunctionTok{c}\NormalTok{(}\DecValTok{25}\NormalTok{, }\DecValTok{100}\NormalTok{)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{\textquotesingle{}S*\textquotesingle{}}\NormalTok{ , }\AttributeTok{y =} \StringTok{\textquotesingle{}estimated cost savings\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept=}\DecValTok{41}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{,}
             \AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \DecValTok{42}\NormalTok{, }\AttributeTok{y =} \DecValTok{140000}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{0}\NormalTok{, }\AttributeTok{fontface =} \DecValTok{2}\NormalTok{,}
           \AttributeTok{label=} \FunctionTok{paste}\NormalTok{(}\StringTok{"maximum estimated cost savings at S* = 41: $136,800"}\NormalTok{), }\AttributeTok{color =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Solution_files/figure-latex/unnamed-chunk-4-1.pdf} The
best value for the threshold \(S^*\) is 41 with approximate cost saving
\$136,800.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{glm.fit }\OtherTok{=} \FunctionTok{glm}\NormalTok{(readmit30}\SpecialCharTok{\textasciitilde{}}\NormalTok{.,}\AttributeTok{data=}\NormalTok{data,}\AttributeTok{family=}\FunctionTok{binomial}\NormalTok{(}\AttributeTok{link=}\StringTok{"logit"}\NormalTok{))}
\CommentTok{\# summary(glm.fit)}
\FunctionTok{stargazer}\NormalTok{(glm.fit, }\AttributeTok{header =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{type =} \StringTok{\textquotesingle{}latex\textquotesingle{}}\NormalTok{, }\AttributeTok{title =} \StringTok{"2 (e)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!htbp] \centering 
  \caption{2 (e)} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & readmit30 \\ 
\hline \\[-1.8ex] 
 age & 0.002 \\ 
  & (0.005) \\ 
  & \\ 
 female & 0.190$^{**}$ \\ 
  & (0.082) \\ 
  & \\ 
 flu\_season & 0.743$^{***}$ \\ 
  & (0.082) \\ 
  & \\ 
 ed\_admit & $-$0.159 \\ 
  & (0.115) \\ 
  & \\ 
 severity.score & 0.027$^{***}$ \\ 
  & (0.002) \\ 
  & \\ 
 comorbidity.score & 0.016$^{***}$ \\ 
  & (0.001) \\ 
  & \\ 
 Constant & $-$4.016$^{***}$ \\ 
  & (0.410) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 4,382 \\ 
Log Likelihood & $-$1,915.831 \\ 
Akaike Inf. Crit. & 3,845.662 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

Let \(\pi\) denote the probability that \(readmit30=1\), then from the
model we constructed, we have
\[logit(\hat{\pi})=-4.016+0.002*age+0.190*female+0.743*flu\_season-0.159*ed\_admit\]
\[+0.027*severity.score+0.016*comorbidity.score\] (f)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# patient’s estimated probability of readmission}
\NormalTok{glm.probs }\OtherTok{=} \FunctionTok{predict}\NormalTok{(glm.fit,}\AttributeTok{type=}\StringTok{"response"}\NormalTok{)  }
\NormalTok{data}\SpecialCharTok{$}\NormalTok{p}\OtherTok{\textless{}{-}}\NormalTok{ glm.probs}
\NormalTok{y}\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\FloatTok{0.01}\NormalTok{)}
\NormalTok{list2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{() }\CommentTok{\# store cost savings}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{10}\SpecialCharTok{:}\DecValTok{90}\NormalTok{) \{}
  \CommentTok{\# filter out the patients with higher estimated prob. being re{-}admitted}
\NormalTok{  T1}\OtherTok{\textless{}{-}}\NormalTok{data[data}\SpecialCharTok{$}\NormalTok{p}\SpecialCharTok{\textgreater{}}\NormalTok{i}\SpecialCharTok{/}\DecValTok{100}\NormalTok{,] }
  \CommentTok{\# number of true re{-}admitted patients among the selected patients}
\NormalTok{  ad}\OtherTok{\textless{}{-}}\FunctionTok{sum}\NormalTok{(T1}\SpecialCharTok{$}\NormalTok{readmit30)}
  \CommentTok{\# saved cost {-} implementation cost = final cost saving}
\NormalTok{  list2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(list2, ad}\SpecialCharTok{*}\DecValTok{8000}\SpecialCharTok{*}\NormalTok{.}\DecValTok{4}\SpecialCharTok{{-}}\FunctionTok{dim}\NormalTok{(T1)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{*}\DecValTok{1200}\NormalTok{)}
\NormalTok{\}}
\NormalTok{Y}\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\FloatTok{0.01}\NormalTok{), list2)}
\FunctionTok{colnames}\NormalTok{(Y)[}\DecValTok{1}\NormalTok{] }\OtherTok{=} \StringTok{\textquotesingle{}p\textquotesingle{}}
\FunctionTok{colnames}\NormalTok{(Y)[}\DecValTok{2}\NormalTok{] }\OtherTok{=} \StringTok{\textquotesingle{}saving\textquotesingle{}}
\CommentTok{\# Find out the maximum cost saving}
\NormalTok{Y[}\FunctionTok{which.max}\NormalTok{(Y}\SpecialCharTok{$}\NormalTok{saving), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      p saving
## 31 0.4 495200
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{seq}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.9}\NormalTok{, }\FloatTok{0.01}\NormalTok{), }\AttributeTok{y =}\NormalTok{ list2)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{scale\_x\_continuous}\NormalTok{(}\AttributeTok{limits=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.9}\NormalTok{)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{\textquotesingle{}p*\textquotesingle{}}\NormalTok{ , }\AttributeTok{y =} \StringTok{\textquotesingle{}estimated cost savings\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \FloatTok{0.4}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{,}
             \AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \FloatTok{0.42}\NormalTok{, }\AttributeTok{y =} \DecValTok{499000}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{0}\NormalTok{, }\AttributeTok{fontface =} \DecValTok{2}\NormalTok{,}
           \AttributeTok{label=} \FunctionTok{paste}\NormalTok{(}\StringTok{"max. cost savings at p* = 0.4: $495,200"}\NormalTok{), }\AttributeTok{color =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Solution_files/figure-latex/unnamed-chunk-6-1.pdf} The
best value for the threshold \(p^*\) is 0.4 with approximate cost saving
\$495,200.

\hypertarget{question3}{%
\section{Question3}\label{question3}}

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  False
\end{enumerate}

P(Y\textbar{}\textbf{X}) denotes the probability that Y belongs to a
particular category given X.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\item
  True
\item
  False
\end{enumerate}

Logistic regression is one of the discriminative classification
algorithms, and it fits a model of the form P(Y\textbar{}\textbf{X}) not
P(\textbf{X},Y).

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  False(?)
\end{enumerate}

\end{document}
